# Generated by Django 4.2.13 on 2024-06-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneAssure', '0002_user_preferred_time_zone_alter_user_dnd_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meetung_type',
            new_name='meeting_type',
        ),
    ]
