# Generated by Django 4.2.13 on 2024-06-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneAssure', '0003_rename_meetung_type_meeting_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='notification_interval',
            field=models.CharField(default='0 10 * * *', max_length=100),
            preserve_default=False,
        ),
    ]
