# Generated by Django 4.2.13 on 2024-06-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneAssure', '0004_meeting_notification_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='notification_interval',
            field=models.DateTimeField(),
        ),
    ]
